### ISSUE TITLE
Make script correctly detect Linux distro, install dependencies and build without errors.

### ISSUE THREAD

**Issue by Megaf** [FlightGearRepublic/FlightGear4Linux#1]
# TODO
## Package list
Define the list of packages required to build PLIB, OpenSceneGraph, SimGear and FlightGear on
- [ ] Debian (Ubuntu, Debian, Mint, Pop, Purism...)
- [ ] Arch (Manjaro, Arch...)
- [ ] Red Had (Fedora, CentOS, Red Hat...)
- [ ] SUSE
- [ ] Clear Linux

# Checklist
## Detects Distro
- [ ] Debian (Ubuntu, Debian, Mint, Pop, Purism...)
- [ ] Arch (Manjaro, Arch...)
- [ ] Red Had (Fedora, CentOS, Red Hat...)
- [ ] SUSE
- [ ] Clear Linux

## Installs Dependencies
- [ ] Debian (Ubuntu, Debian, Mint, Pop, Purism...)
- [ ] Arch (Manjaro, Arch...)
- [ ] Red Had (Fedora, CentOS, Red Hat...)
- [ ] SUSE
- [ ] Clear Linux

## Builds Successfully
- [ ] Debian (Ubuntu, Debian, Mint, Pop, Purism...)
- [ ] Arch (Manjaro, Arch...)
- [ ] Red Had (Fedora, CentOS, Red Hat...)
- [ ] SUSE
- [ ] Clear Linux
